name: qofheart
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  custom_pop_up_menu: ^1.2.4
  flutter_animate: ^4.5.0
  http: ^1.2.2
  get: ^4.6.6
  flutter_toggle_tab: ^1.4.1
  go_router: ^14.2.6
  dio: ^5.6.0
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.1
  get_storage: ^2.1.1
  fluttertoast: ^8.2.8
  carousel_slider: ^5.0.0
  custom_pin_keyboard: ^0.0.4
  focus_detector: ^2.0.1
  local_auth: ^2.3.0
  flutter_native_contact_picker: ^0.0.8
  share_plus: ^10.0.2
  app_bar_with_search_switch: ^1.8.5
  flutter_screen_lock: ^9.1.0
  pin_lock_screen: ^1.0.1
  text_marquee: ^0.0.2
  screenshot:
  onesignal_flutter: ^5.2.5
  cached_network_image: ^3.4.1
  url_launcher:
  awesome_dialog: ^3.2.1
  upgrader: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_native_splash:
  android: true
  ios: true
  web: false

  color: "#29B7FF"
  image: "assets/images/app_icon.png"

  android_12:
    image: "assets/images/app_icon.png"
    icon_background_color: "#29B7FF"