name: Flutter APK & AAB Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.3'

    - name: Install dependencies
      run: flutter pub get

    - name: Ensure Flutter is ready
      run: flutter doctor

    - name: Build APK
      run: flutter build apk --release

    - name: Build AAB
      run: flutter build appbundle --release

    # Upload APK as artifact (Updated to v4)
    - name: Upload APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: flutter-app-release.apk
        path: build/app/outputs/flutter-apk/app-release.apk

    # Upload AAB as artifact (Updated to v4)
    - name: Upload AAB as artifact
      uses: actions/upload-artifact@v4
      with:
        name: flutter-app-release.aab
        path: build/app/outputs/bundle/release/app-release.aab
